---
name: privacy-embed
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'zazama/privacyembed:client/css/tinymce.css'
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Zazama\PrivacyEmbed\Extensions\SiteConfigExtension
