---
name: privacy-embed
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'wakeworks/privacyembed:client/css/tinymce.css'
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - WakeWorks\PrivacyEmbed\Extensions\SiteConfigExtension
